### ISSUE TITLE
Wish: Add flow summary information (txt and geojson)

### ISSUE THREAD

**Issue by PySjon** [nens/batch-calculator#20]
I see that the model shows weird behaviour during the t10 rain event. Now I do not know during which events the model crashed.
Adding model run flow summaries would resolve this issue and make it a little less of a black box.

**Comment by daanvaningen** [comment]
Flow summaries and other simulation data are not included in when downloading the simulation results because this resulted in quite a lot of data. This sometimes caused problems on the consultants task server depending on the amount of personal available space.

The `created_simulations` json file contains all the information needed to find the results. Is this enough for you to find the results you are looking for or do we need a separate script to download the results?

**Comment by PySjon** [comment]
It is not enough. Because I can't link result outcomes to specific rain
events. So if one location shows weird results because one modelrun
malfunctioned, I can't find that specific modelrun.

**Comment by daanvaningen** [comment]
fixed in https://github.com/nens/batch-calculator/pull/21
